### ISSUE TITLE
TheHive 4.0 for migration

### ISSUE THREAD

**Issue by JamesCullum** [TheHive-Project/Docker-Templates#29]
We are using a dockerized Hive at version 3.4. According to the migration path, I would need to upgrade to 4.0 first before going to 4.1. What is the recommended way to do this?

From my understanding the solution would be to have a Docker template for 4.0, run it and migrate, then run and upgrade 4.1 with the same data?

**Comment by nadouani** [comment]
Yes, You need to have a 4.0.5 to migrate from 3.4 and then upgrade your 4.0.5 to 4.1.x

**Comment by JamesCullum** [comment]
This wasn't supposed to be a question, but a request to add a template that can be used for this migration. At the moment there is no 4.0 version.
